POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MDQ3MTk5MjYsInVzZXJJZCI6MX0.IkKl0XHg7VN3l97Etrofhn0SooCDn92NPqlldyoDBzQ
